import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'NextDocs',
  description: 'Generated by Dhuruv',
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </>
  )
}
